imports:
    - { resource: 'services.yml' }

parameters:
    supported_languages: ['lt', 'en', 'ru', 'lv', 'ee', 'et', 'pl', 'bg']
    default_language: 'en'
    widget_js: 'https://bank.paysera.com/new/js/project/wtpQualitySigns.js'

    module_settings:
        configuration:
            PAYSERA_PROJECT_ID: 123456
            PAYSERA_PROJECT_PASSWORD: ''
            PAYSERA_TESTING_MODE: 1
            PAYSERA_DISPLAY_PAYMENT_METHODS: 1
            PAYSERA_DEFAULT_COUNTRY: 'lt'
            PAYSERA_DISPLAY_WIDGET: 0
            PAYSERA_INCLUDE_VERIFICATION: 0
            PAYSERA_VERIFICATION_CODE: ''
            PAYSERA_AWAITING_PAYMENT_ORDER_STATE_ID: ~

        order_states:
            - { name: 'Awaiting Paysera payment', color: '#206f9f', paid: 0, config: 'PAYSERA_AWAITING_PAYMENT_ORDER_STATE_ID'}

        tabs:
            - { name: 'Paysera', class_name: 'AdminPayseraConfiguration', ParentClassName: 'AdminParentPayment' }

        hooks:
            - 'moduleRoutes'
            - 'paymentOptions'
            - 'displayOrderDetail'
            - 'actionFrontControllerSetMedia'
            - 'header'